local CHEMICAL = Wizardry.Objects.NewChemical("aotraz.ants")
CHEMICAL:SetName("A Bottle of Ants")
CHEMICAL:SetDescription("Yes. That's it. Don't ask why they're so expensive.")
CHEMICAL:SetPrice(aotraz_potions.Config.Ants)
CHEMICAL:Define()
