local CHEMICAL = Wizardry.Objects.NewChemical("aotraz.cyanide")
CHEMICAL:SetName("Cyanide")
CHEMICAL:SetDescription("Enjoying the taste of death since 1782!")
CHEMICAL:SetPrice(aotraz_potions.Config.Cyanide)
CHEMICAL:Define()
