local CHEMICAL = Wizardry.Objects.NewChemical("aotraz.meth")
CHEMICAL:SetName("Meth")
CHEMICAL:SetDescription("For uh... scientific purposes... That makes it legal, right?")
CHEMICAL:SetPrice(aotraz_potions.Config.Meth)
CHEMICAL:Define()
